name: watch

on:
  schedule:
    - cron: "5 */2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  custom-catalog:
    uses: grafana/k6-extension-registry/.github/workflows/custom-catalog.yml@main
